### ISSUE TITLE
VS Code not detected

### ISSUE THREAD

**Issue by FrankFromGermany** [didierterrien/Power-BI-Sidetools#1]
Where or how do I have to install VS Code to be detected?

Files -> Open VS Code ->
or
Folders -> Open projects folder in VS Code ->

![image](https://user-images.githubusercontent.com/26203785/97973035-bb1dfe80-1dc5-11eb-9db1-0fdf37399a4d.png)

Error opening process: "The system could not find the requested file" (translated)

![image](https://user-images.githubusercontent.com/26203785/97973490-6d55c600-1dc6-11eb-8ffc-2c9918cba845.png)

**Comment by didierterrien** [comment]
Hello Franck,

Thank you for the feedback !

At the moment, Sidetools launches VS code from this path like it is installed on my machine : 
   C:\Users\username\AppData\Local\Programs\Microsoft VS Code\Code.exe
Today, I will attach a new beta version in this issue with a correction for your VS Code path.
Later, I will get the installation path from the registry.
Sorry for the disturbance

Didier

**Comment by didierterrien** [comment]
Franck,

Here is the preview version. Please tell me if you have any issue with it.

[Power-BI-Sidetools V1.1.1 preview.zip](https://github.com/didierterrien/Power-BI-Sidetools/files/5483612/Power-BI-Sidetools.V1.1.1.preview.zip)

This version's purpose is to work with VS code installed in "C:\Program files\Microsoft VS Code\Code.exe"

Didier

**Comment by didierterrien** [comment]
V1.1.1 have been published
