### ISSUE TITLE
Sidetools does not work when projects folder is pointed to within my Documents folder in OneDrive

### ISSUE THREAD

**Issue by hcc-donder** [didierterrien/Power-BI-Sidetools#10]
By default, the projects folder is in C:\Users\user\Documents\Power BI Sidetools. However, my Documents folder is not at this location, but is in my OneDrvie instead (C:\Users\user\OneDrive - organization name\Documents). When I change the project folder to be within this folder, Sidetools no longer works - at all. The directory name is only 82 characters long, so that does not seem to be the issue and I was able to use a project folder in another location with a space in the name, so that does not seem to be the issue either. I will use it in the default folder for now, but would much rather have it in my OneDrive folder.

**Comment by didierterrien** [comment]
Hello David,
Thank you for the feedback. I suppose when you say "Sidetools no longer works", you mean "PBI to files" no longer works but other features work.
It's working on my computer. My folder is :   "C:\Users\username\OneDrive - companyname\Test" so it's comparable to yours.
Did you navigate to the OneDrive folder using the ellipsis (...) or did you type it ?
Do you have admin user rights on your computer ?
Have a good day

**Comment by hcc-donder** [comment]
In my case, none of the features of SideTools were working. I figured out the problem after you said you had it working just fine. I have controlled folder access on my OneDrive folder and SideTools did not have permission to access that folder. I moved the Power BI SideTools folder into a non-controlled folder and it worked fine. I did not realize it was being blocked because it was silent about the error. Normally, Windows tells me when a app is trying to access a controlled folder but this time it did not.

Thanks for following up. This is a great tool and I look forward to using it in the future.
David

Mr. David Onder, MAEd  |  Director and SACSCOC Liaison
Institutional Excellence, Research, and Grants  |  Balsam 121
Haywood Community College |  185 Freedlander Drive  |  Clyde,<http://goo.gl/maps/CV2c> NC 28721
828.565.4077<tel:+18285654077> tel  | 828.627.4523<mailto:828.565.4077>  fax  |  828.627.2821<tel:+18286272821> main |  ***@***.******@***.***>
https://www.haywood.edu/institutional-excellence-research-and-grants
https://zoom.us/my/hcc-donder

President of CCPRO<http://ccpro.org/> and member of NCAIR<https://www.ncair.net/>

Submit a ticket: https://tickets.haywood.edu/

"Everyone is right, depending on the situation and context." Andre Karpistsenko<http://www.kdnuggets.com/2015/04/data-scientists-thoughts-that-inspire.html>

NOTICE: All e-mail correspondence to and from this address is subject to the North Carolina Public Records Law, which may result in monitoring and disclosure to third parties, including law enforcement.

**Comment by didierterrien** [comment]
David,
I will control if the folder is read only and will display a message.  Let's keep the issue open until I will do it.
Thank you for your help to make Sidetools better. 
Didier

**Comment by didierterrien** [comment]
Hello David,
I improved file access error detection in version 1.2.1 published yesterday. 
I close the issue but feel free to re open it if necessary.

**Comment by dmonder** [comment]
Nice. Thank you for fixing that. I just tested it and it worked well.
