### ISSUE TITLE
External Tools Manager loads at top left overlapping taskbar if you have it loaded at top

### ISSUE THREAD

**Issue by alliedcvil** [didierterrien/Power-BI-Sidetools#17]
I'm one of the rare users that uses my Win taskbar at the top instead of the bottom. Since the External tools manager loads at the Y:0 coordinate I assume it the taskbar is overlapping the top of the External tools window. The only way to move it is by right clicking the icon and selecting move from the taskbar which can be confusing to some. If possible is there a way you can have it detect the location of the taskbar and prevent it from loading behind it.

**Comment by didierterrien** [comment]
Hello,
Thanks for the feedback !
In the next version (V1.2.2), windows default position will be center  of the screen
