### ISSUE TITLE
Custom Installation Path not working

### ISSUE THREAD

**Issue by fdawans** [didierterrien/Power-BI-Sidetools#2]
Hello,

Thank you for your app, it will be very useful to export the M/DAX code to VSCode and Git.
I changed the default installation path (_C:\Program Files (x86)\The BI Power\Power BI Sidetools\_) but then PowerBI Sidetools is not working in PowerBI - see picture.
I made it work after reinstalling with the default path.

![PB SideTools](https://user-images.githubusercontent.com/53601011/100229888-35552500-2f25-11eb-9c0c-aac2ff77ba10.png)

**Comment by didierterrien** [comment]
Hello,
Thank you for the report.
If you change the installation folder of Power BI Sidetools, you need also to change the path in the Json file located here:  "C:\Program Files (x86)\Common Files\microsoft shared\Power BI Desktop\External Tools\powerbisidetools.pbitool.json"

![image](https://user-images.githubusercontent.com/37301981/100232380-96cac300-2f28-11eb-9d92-2ddaa36dcd83.png)

Please notice, there are doubled separators \\

I close the issue but feel free to reopen it if necessary
Regards
