### ISSUE TITLE
Power BI Sidetools

### ISSUE THREAD

**Issue by DavidSM3** [didierterrien/Power-BI-Sidetools#20]
Hi,

Thank you for producing a wonderful tool.

Unfortunately I am unable to get the DAX debugger working, am I missing something?

Kind Regards
David

**Comment by didierterrien** [comment]
Hello David,
Thank you.
Did you look at the demo in Reid Havens channel ? 
          [https://www.youtube.com/watch?t=3526&v=z04v4vy7T50&feature=emb_imp_woyt](https://www.youtube.com/watch?t=3526&v=z04v4vy7T50&feature=emb_imp_woyt) 
and did you check the blog post ? 
         https://thebipower.fr/index.php/2021/04/05/dax-debugger/
Do you use a live connection ? Sidetools doesn't work with live connections at the moment.
First, try with a very simple measure.
If any of these don't help, please send a screenshot of your report and Sidetools window.
Regards
Didier Terrien

**Comment by DavidSM3** [comment]
Hi Didier
Thank you for your prompt reply, the demo was what sparked my interest, I believe I have found the issue.
It does not find measures in a calculated table, my measures table was created by  using the function DATATABLE

PrimaryMeasures = DATATABLE("Dummy",STRING, {{"a"}})

I have changed this by using "Enter Data" option on the ribbon and it now works

Thank you again, regards

David

**Comment by DavidSM3** [comment]
Hi Didier

It appears that your code does not search “calculated tables” for measures, my measure table was a calculated table.

Would it be possible to obtain the latest version on “Power-BI Sidetools”, my version does not allow me to edit my measures in Visual Studio Code and update in the PBIX

Kind Regards
David

Sent from Mail for Windows 10

**Comment by didierterrien** [comment]
Hello David,

It normally works for calculated tables. As they are tables, you need to type their name in the second field. First field is for measures and calculated columns. Of course they need to be created without error and appear already in the desktop as a table.

At the moment, Sidetools doesn't write back from files to Power BI desktop.
I worked already on this functionality and it works well for measures as it is supported by Microsoft. At the moment, writing to a model through XMLA endpoint is not supported by Microsoft for calculated columns and calculated tables. Modifications don't appear immediately in the desktop even if they are transfered properly. It is necessary to save the pbix then reopen it to see modifications. It is confusing for users.

There is an other question to solve : as it will be possible to modify DAX formulas in VS code and in Power BI desktop at the same time there might be conflicts. So controls must be done but they are not developed yet.

Thanks for your interest in Power BI Sidetools

**Comment by DavidSM3** [comment]
Thank you very much for your prompt response, I love the tool

Sent from Mail for Windows 10
