### ISSUE TITLE
Measures saved under a calculated table are not exported to files

### ISSUE THREAD

**Issue by b-per** [didierterrien/Power-BI-Sidetools#21]
HI!

Just found a quick bug. 

We have created a dummy calculated table and stored our measures under this table. When exporting measures and calculated tables to files, the calculated table shows with `CT` but the measures saved under this calculated table don't get exported.

![image](https://user-images.githubusercontent.com/8754100/120919771-9fcdf580-c6fe-11eb-855d-3226e0ba3962.png)

Cheers,
Benoit.

**Comment by didierterrien** [comment]
Thanks a lot Benoit for the feedback. I will check it quickly. It will be solved in the next version.

**Comment by didierterrien** [comment]
Hello Benoit,
Version 1.2.3 has been published solving this issue.
Thanks for your contribution

**Comment by b-per** [comment]
The fix works perfectly!
