### ISSUE TITLE
PBI to files when PBI is saved, constantly refreshes

### ISSUE THREAD

**Issue by hlynurarni** [didierterrien/Power-BI-Sidetools#24]
When the option "PBI to files when PBI is saved" is used it constantly executes and creates the files again. I have the folder structure open and I see the files disappear and show again in intervals of few seconds without me doing any action.

Only thing I have changed is the path to where I save the files, seems to me that this triggers this constant refresh. I have the folder with a dummy name on the same level as the .pbix.

**Comment by didierterrien** [comment]
Never had this behaviour. I understand, the default folder is the folder where the pbix report is saved. If you move the default folder, it works. Do you confirm ?

**Comment by hlynurarni** [comment]
It is the other way around. The default folders works just fine. But when I change the directory to be on the same level as the .pbix file, this happens. 

To clarify: I create a folder with a dummy name next to the .pbix file, since I cant have 2 files (folder) with the same name. I then point the "pbi to files" to export to that folder.

**Comment by hlynurarni** [comment]
EDIT: 7.16.2021
Some new discoveries on this issue that is linked to https://github.com/didierterrien/Power-BI-Sidetools/issues/25 

I have tried with different .pbix files and it happens if I have the following setup:

Settings and folder structure:

![default_path](https://user-images.githubusercontent.com/10733420/125922683-7e54e26d-2f54-4f62-b4c2-9a42481ca402.png)

The connection I got when I opened after I changed the path: 

![GUID_settings](https://user-images.githubusercontent.com/10733420/125923219-19875cae-6c87-4994-8e1e-c40736a15a98.jpg)


![path1](https://user-images.githubusercontent.com/10733420/125921761-d6b43740-5732-43cd-9b5d-6f785e382391.png)

(1) I ran into the GUID issue and this happened (I attached the log files). Apparently the files seems to be in another process, I just had one file open and nothing running. **Here I had no issue with constant refresh.**


![path2](https://user-images.githubusercontent.com/10733420/125921767-66d0ae9c-6459-4def-8410-03d460b59f70.png)

(2) I relaunched PBi Desktop and there was no write access conflict anymore (according to the log file) and that created this folder structure. **Here I had constant refresh.**

![after_relaunch](https://user-images.githubusercontent.com/10733420/125923634-4920222f-9927-48dc-80a9-4dbec2ca963b.png)

Constant refresh on those folders: 

![constant_refresh](https://user-images.githubusercontent.com/10733420/125923843-ae2b221b-4f5f-454c-ace3-d7f6ef7c42ef.png)


The log file:

[Power BI Sidetools log.txt](https://github.com/didierterrien/Power-BI-Sidetools/files/6829403/Power.BI.Sidetools.log.txt)


Hope this helps, don't hesitate to ask if there is anything unclear, I tried to display it as best as I could.

**Comment by didierterrien** [comment]
Thanks a lot for your explanations. 
The constant refresh error must be solved in V1.2.5 test version :
[https://github.com/didierterrien/Power-BI-Sidetools/tree/master/Power%20BI%20Sidetools%20test%20versions](https://github.com/didierterrien/Power-BI-Sidetools/tree/master/Power%20BI%20Sidetools%20test%20versions)

**Comment by hlynurarni** [comment]
Thank you for the quick replies and new version. The refresh problem has gone away with the latest version V1.2.5. Great work on the relative path feature, much appreciated !
