### ISSUE TITLE
GUID extension added to folder name

### ISSUE THREAD

**Issue by hlynurarni** [didierterrien/Power-BI-Sidetools#25]
I can't figure out why this happens but sometimes when you launch SideTools there is an extension (GUID I assume) added to the folders name. After that you can't execute an action like "pbi to files". I highlight the middle out since I don't know if there is any information in it.

![Screenshot 2021-07-13 135710](https://user-images.githubusercontent.com/10733420/125448352-2801e627-0150-4472-9e2a-297244975fc7.png)

**Comment by didierterrien** [comment]
I never had this issue. I don't know how to reproduce the problem. Does it happen with some pbix files and not with others ? Where is located the pbix file ? What are your settings ?
There is a log file in the default folder. Can you send it to me ?

**Comment by hlynurarni** [comment]
I tried different things and couldn't figure out what really causes it. I am experimenting a lot with the tool so I am launching it often, changing the directory save path, changing autosave and features like that. I will try to reproduce during next days. Not a major bug at the moment but just unexpected behaviour.

Setup:
.pbix is located on a shared one drive and I have pointed the "pbi to files" directory to be close to it but not on the same level because of a constant refresh (https://github.com/didierterrien/Power-BI-Sidetools/issues/24). I get a new log file at that location, will send it and give you a more detailed info about my settings when this happens.

**Comment by didierterrien** [comment]
Thanks for explanations !
Can you try on a local hard drive instead of one drive ? 

Then, you can try also with the V1.2.5 test version :
[https://github.com/didierterrien/Power-BI-Sidetools/tree/master/Power%20BI%20Sidetools%20test%20versions](https://github.com/didierterrien/Power-BI-Sidetools/tree/master/Power%20BI%20Sidetools%20test%20versions)

**Comment by hlynurarni** [comment]
You are correct that OneDrive seems to be the issue here. I tried the new version on OneDrive and got this error after some tries of replicating it.

**Comment by didierterrien** [comment]
I will try also with One Drive

**Comment by hlynurarni** [comment]
This seems to be fixed in the updated version. After restart I have tried numerous times to recreate the problem without success. This can be considered closed.

**Comment by didierterrien** [comment]
Thank you for your contribution
