### ISSUE TITLE
No connection through External Tools button

### ISSUE THREAD

**Issue by hlynurarni** [didierterrien/Power-BI-Sidetools#26]
With some reports I can't establish a connection by using the external tool button. Those reports do not include M or DAX code if that matters. I can establish a connection with other reports open beside it at the same time.

I have used the workaround of typing into search "sidetools" and run the app from there, that has worked for me.

Below are screenshots of how I experience the problem:

When I use the External Tools button: 
![no_connection](https://user-images.githubusercontent.com/10733420/126308235-a39e7696-dd98-4f0a-965c-796d5f75de12.png)

When I launch the app through search
![run_search](https://user-images.githubusercontent.com/10733420/126308276-a256ee9c-3880-44b8-a693-3d8df0c9301e.png)

Then I get the connection like this
![succ_connection](https://user-images.githubusercontent.com/10733420/126308314-08025668-5250-4ade-9843-4ad3f1e78c27.png)

**Comment by didierterrien** [comment]
At the moment, Sidetools doesn't work with live connected pbix. 
I agree the behaviour you describe looks strange. Can you share a report so I can try to reproduce the different behaviours ?

**Comment by didierterrien** [comment]
And can you send to me the log file please ?

**Comment by hlynurarni** [comment]
I will have to figure out a way to strip the report so I can send it. But yes it is connect directly to Power Bi service.

[Power BI Sidetools log.txt](https://github.com/didierterrien/Power-BI-Sidetools/files/6847998/Power.BI.Sidetools.log.txt)

**Comment by didierterrien** [comment]
Thank you.
When you launch the external tool, the log must show the command line like this :
[07-19-2021 17:39:20]  Command line : "localhost:59746" "688f66d7-adc0-4234-9a4d-8296b6379e82"
Did you remove these lines ?

**Comment by hlynurarni** [comment]
I have not edited the log file

**Comment by didierterrien** [comment]
It's my mistake, the next version will show the command line.

**Comment by didierterrien** [comment]
I published V1.2.6 test version. Can you try it ?

Test version 1.2.6 is meant to 
	- evaluate the new auto update feature. It tries systematically to update to the production version. When you will finish to evaluate V1.2.6, please try to update and provide feedback about possible issues.
	- improve connection with reports connected to Power BI datasets
	- evaluate the preview version of DAX generator

DAX generator provides 2 files repositories containing DAX formulas. One contains your own DAX templates (user templates) and the second one contains DAX templates written by experts (featured templates).
Those templates contain	a DAX formula and several instructions for the DAX generator. Instructions declare parameters so the user can change the measure name, tables name, columns names, values in few clicks.
Then the user generates the DAX formula which can be pasted in Power BI desktop, Tabular Editor, DAX Studio, ... DAX generator provides the possibility to create or update measures with one click in the desktop. An other click allows to debug DAX formulas in DAX debugger.

**Comment by hlynurarni** [comment]
This is the message I get when I launch sidetools:

![image](https://user-images.githubusercontent.com/10733420/132867949-211f5ad4-8e66-4b17-ba41-2e180cabe951.png)

I do not have the ability to run SideTools from my search bar anymore...

The update feature looks nice but after I hit process I get download packages and another message that goes too quickly away (installation something)

I get both this: 

![image](https://user-images.githubusercontent.com/10733420/132874070-503fdace-6366-4939-8c18-6fb6ba6bcd62.png)

And this: 

![image](https://user-images.githubusercontent.com/10733420/132869170-d85733e4-3cad-4f07-baa7-fc0df4c2be58.png)

![image](https://user-images.githubusercontent.com/10733420/132872220-4bb159d3-4237-4df5-9110-254df8ccb68e.png)

When I try to install the test version again I sett a update message if I want to remove or repair my program (have not noticed that before)

![image](https://user-images.githubusercontent.com/10733420/132870835-d6066b57-bf47-4941-8e93-3824b63add9a.png)

I will later evaluate the DAX additions, but I can see it is there. 

![image](https://user-images.githubusercontent.com/10733420/132874394-447dbf11-3b2f-441e-b656-948aeb4e3d14.png)

![image](https://user-images.githubusercontent.com/10733420/132874359-a2956003-8501-45e4-a0bd-3c8689086356.png)

**Comment by didierterrien** [comment]
Thank you very much for your tests !

1. 'Power BI Sidetools warning' window is normal as there is no model available in the Pbix even if you create measures in the thin report. Daniel Otykier mentionned it might change.

2. I added back the shortcut so I suppose you can launch Sidetools from the search bar now

3. The 'Update control' small window was not supposed to appear. I removed it. The bigger one is correct. If you click on 'Process', you revert to version 1.2.5. You need to install again V1.2.6 if you want to test it more

4. The messages you got in the 'Power BI Sidetools update' are normal

5. You chosed correctly 'Repair' in  the install window. This dialog will disapear in the production release. 

6. The Zip file you saw will be uncompressed and deleted when you will launch DAX generator for the first time. It contains featured templates (templates created by experts). At the moment, there are only 2 templates for the demo.

**Comment by didierterrien** [comment]
I published a new V1.2.6 version with these corrections

**Comment by hlynurarni** [comment]
I am NOT able to use the update to new version feature that you introduced in the test version v1.2.6. Hitting the process does not work, there comes an error that goes really quickly but I managed to capture it: 

![image](https://user-images.githubusercontent.com/10733420/133426333-bda774ea-d93f-4fee-aed7-123868fb87da.png)

The layout folder I am missing in live reports ([Discussion](https://github.com/didierterrien/Power-BI-Sidetools/discussions/27)). I cant reproduce it with the test version since I get the same "live reports..." message even though I launch it from the search menu.

**Comment by didierterrien** [comment]
Thank you for your investigations !
I corrected some issues with thin reports. With version 1.2.7, you are supposed to be able to run PBI to files on a thin report whenever you run Sidetools from 'External tools' tab or from the search bar : 
- You get a warning message when Sidetools starts
- The port number is orange instead of green
- You cannot use some features which require a model like DAX debugger, DAX & M export to files, Export to Excel, ...
 
But you get at least the layout files

The installation error is traced in the log file. Please send it to me if auto update still doesn't work
You will need to uninstall V1.2.5 manually at the end of your tests

**Comment by didierterrien** [comment]
Thin reports are better supported with latest versions. They are still not fully supported. I close the issue. Feel free to reopen it with  explanations.
