### ISSUE TITLE
PBI to files - Illegal characters in path

### ISSUE THREAD

**Issue by fdawans** [didierterrien/Power-BI-Sidetools#3]
I have an error in the path when exporting my DAX measures.
M code is exporting fine.

Thank you for your help,

![IllegalPath](https://user-images.githubusercontent.com/53601011/100230370-f2e01800-2f25-11eb-86ec-6eff0271be89.png)

**Comment by didierterrien** [comment]
Hello,
Thank you to report this issue. 
Did you change the default path for the DAX code in the settings ? If yes, send it to me please.
What is the version you use ? 
Can you copy all the text of the error here ?

**Comment by fdawans** [comment]
I am using Version 1.1.2.0.
No, I reinstalled and kept the original path.

Doesn't seem to be the issue as M files are created, but my documents are on a network drive at:
_\\xxxxxx.net\HD\u548868\MyDocuments_ and the files are created at the default location _C:\Users\u548868\Documents\Power BI Sidetools_

In the DAX folder, I have a folder that says "T_  _Office Supply"
![VSCode](https://user-images.githubusercontent.com/53601011/100248745-229a1a80-2f3c-11eb-91ac-8f6b47e0abe3.png)

See log:
[LogPBI.txt](https://github.com/didierterrien/Power-BI-Sidetools/files/5597632/LogPBI.txt)

**Comment by didierterrien** [comment]
Yes, any character forbidden in path by Windows will not work, I can replace these characters automatically by their ASCII code. So a measure called Measure * 6 will be renamed as Measure &h3C 6.
Is it ok for you ? 

Forbidden characters by Windows :
< (less than)
> (greater than)
: (colon - sometimes works, but is actually NTFS Alternate Data Streams)
" (double quote)
/ (forward slash)
\ (backslash)
| (vertical bar or pipe)
? (question mark)
* (asterisk)

**Comment by fdawans** [comment]
OK got it, I'll keep it in mind when naming my measures!

**Comment by didierterrien** [comment]
Problem solved in V1.1.3
