### ISSUE TITLE
Auto-update feature in version 1.2.6 incorrectly identifies current version

### ISSUE THREAD

**Issue by JamesDBartlett3** [didierterrien/Power-BI-Sidetools#30]
After installing version 1.2.6 and launching it from the External Tools menu, it pops up a dialog box telling me the installed version is out of date, and asks if I want to update. It seems to be identifying itself as version 1.2.0 rather than 1.2.6. I double-checked the version number in the About tab, and it is indeed 1.2.6, though there is an extra ".0" on the end, so maybe that has something to do with it. 
![image](https://user-images.githubusercontent.com/37491308/132880236-b16b2690-2241-49d1-b828-612ad07d7974.png)
![image](https://user-images.githubusercontent.com/37491308/132880490-18146d38-03ab-4f0e-8bd5-3bc2708d7e27.png)

**Comment by didierterrien** [comment]
Thank you James for reporting. That was made on purpose in order to force autoupdate. I agree it was a bit quick and dirty but I thought nobody will notice it. It seems I was wrong :)
Your sharp eye is very much appreciated !

**Comment by didierterrien** [comment]
I published a new Zip file for the test 1.2.6 version which corrects some small bugs
