### ISSUE TITLE
Relative path not working

### ISSUE THREAD

**Issue by hlynurarni** [didierterrien/Power-BI-Sidetools#33]
When using relative path, SideTools keep saving files into the default sidetools folder.

C:\Users\<username>\Documents\Power BI Sidetools

Here is the log file:

[Power BI Sidetools log.txt](https://github.com/didierterrien/Power-BI-Sidetools/files/8140430/Power.BI.Sidetools.log.txt)

Settings:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/10733420/155700353-22aa67e8-ea79-4c55-bc8a-507eeda5a1e1.png)

**Comment by didierterrien** [comment]
Hello,
Thank you for the log file !
Your Sidetools version seems very outdated (1.2.5). Current version is 1.2.15
Can you update Sidetools and retry with a simple pbix file in import mode before trying with your files ?

**Comment by hlynurarni** [comment]
Will do that, thank you

**Comment by didierterrien** [comment]
I closed the issue. Feel free to re open it with explanations please
