### ISSUE TITLE
PBI to files - Default folder

### ISSUE THREAD

**Issue by fdawans** [didierterrien/Power-BI-Sidetools#4]
Hello,

I tried to change the default saved folder and restarted everything but it did not work.
I would like to point it to my Git repository that looks like this:
Git \ Reports \ Report A \ M & DAX Files
Git \ Reports \ Report B \ M & DAX Files

Add the Git\Reports path to PowerBI SideTools that would then create the Report A/Report B folders for each report with the M & DAX files within.

**Comment by didierterrien** [comment]
Hello,
Thank you to report.
Yes, at the moment, it doesn't work straight in Git repository. You can work in a local folder and connect this folder to the Git repository. Do you use Github ot Gitlab ?
Let me know if it helps

**Comment by fdawans** [comment]
Yes, I meant exporting the files to my local Git folder that I sync with Github through VScode.

**Comment by didierterrien** [comment]
The Git functions are not dependent of Power BI Sidetools.
Can you list the actions you do so I can reproduce the error ?

**Comment by fdawans** [comment]
Right, the problem is not in Git.
I change the project path, then I close PBI and Sidetools but the path is not saved when I reopen.
Thank you.

**Comment by didierterrien** [comment]
I understand now.
Problem solved in V1.1.3. I will publish it tomorrow
Thank you for your help !

**Comment by fdawans** [comment]
Great, I will test it and let you know if everything works fine.

**Comment by didierterrien** [comment]
V1.1.3 is published solving the settings problem
I close this issue but feel free to reopen it if necessary
