### ISSUE TITLE
PowerBI december version

### ISSUE THREAD

**Issue by mackjb** [didierterrien/Power-BI-Sidetools#5]
I think the evolution of Power BI Desktop is causing some troubles in the ability to take back the dax and M code.

**Comment by didierterrien** [comment]
Hello,
Thank you to report the issue. I have no problem with the second version of the desktop from December.
Do you use the version from the windows store or the one for the report server or the one downloaded from the community blog? 
Do you use the Power BI Sidetools version V1.1.4 ?
Could you please decribe what is happening ? No file or corrupted file ? ...
Is the issue happening with several pbix file ?
Which settings do you have ?
Regards

**Comment by mackjb** [comment]
I have done a mistake using the tool, I forgot to firstly click on "PBI to files" before clicking on "Open vs Code"
My bad, I'm very sorry for the disturbance.

We are going to test more the tools and let you know, it seems great for saving the source code associated in devops.

Thanks a lot for your feedback.

**Comment by didierterrien** [comment]
No problem. Thank you for your interrest in the tool
There is a setting which will create/update the files each time you open Sidetools and another one each time the pbix is saved so you don't need to click on PBI to files.
Feel free to make propositions and your feedback about devops will be be extremely valuable.
New functionalities are coming soon. Enjoy Sidetools
