### ISSUE TITLE
Move instructions from blog to README.ME

### ISSUE THREAD

**Issue by gbrueckl** [didierterrien/Power-BI-Sidetools#8]
would be great if the information that can be found on the blog would also be moved to the README.ME of this repo
https://thebipower.fr/index.php/power-bi-sidetools/

would also be nice to link the VSCode extensions directly:
https://marketplace.visualstudio.com/items?itemName=jianfajun.dax-language
https://marketplace.visualstudio.com/items?itemName=PowerQuery.vscode-powerquery

**Comment by didierterrien** [comment]
Hello Gerhard,
I added both links in the blog. Thanks for the proposition.
I don't understand why you want me to duplicate information from the blog to the README file. It will be much more difficult to maintain and it will need a lot of pagination in the README. How can it be more comfortable to read in the README ?

**Comment by gbrueckl** [comment]
maybe it is just a/my personal preference to have everything in one place
speaking of my own github repos I like to have this information in the README so I can easily update when I push new changes instead of having to push the code and maintaining an additional page

was just an idea - and thanks for updating the links, I think it makes it easier for everyone
